name: Build Doc

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install .
          sudo apt-get install pandoc

      - name: Deploy
        uses: mbruno46/deploy-sphinx-doc@v0.1
        with:
          path: doc
          doc-branch: 'documentation'
          pypackages: 'nbsphinx IPython pandoc'
